"""initial revision

Revision ID: 7b86c9f2134e
Revises: 
Create Date: 2023-01-30 16:36:26.129329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b86c9f2134e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('phone_num', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('notification', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_user')
    # ### end Alembic commands ###
